
CFLAGS=-g -Wall -O0 -I/home/dcjones/src -L/usr/local/lib

all : bam_binned_coverage

bam_binned_coverage : bam_binned_coverage.c
	gcc $(CFLAGS) -o bam_binned_coverage bam_binned_coverage.c -lbam -lz


