#!/usr/bin/python

# replace ensembl chromosome numbers with UCSC chromosome names.

from sys import (stdin,stdout)
import re



pat = re.compile( r'^\d+$' )


for line in stdin:
    row = line.split('\t')

    if pat.match(row[0]):
        if int(row[0]) < 100:
            row[0] = 'chr' + row[0]
    elif row[0] in ('X','Y'):
        row[0] = 'chr' + row[0]
    elif row[0] == 'MT':
        row [0] = 'chrM'

    stdout.write( '\t'.join(row) )



